// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelecomBoliviaNet.Infrastructure.Data;

#nullable disable

namespace TelecomBoliviaNet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Admin.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigs", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewData")
                        .HasColumnType("text");

                    b.Property<string>("PreviousData")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Auth.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentTo")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Auth.TokenBlacklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token");

                    b.ToTable("TokenBlacklists", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.ToTable("UserSystems", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("GpsLatitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("GpsLongitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<bool>("HasTvCable")
                        .HasColumnType("boolean");

                    b.Property<string>("IdentityCard")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstalledByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LocationRef")
                        .HasColumnType("text");

                    b.Property<string>("OnuSerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhoneMain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneSecondary")
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TbnCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WinboxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityCard")
                        .IsUnique();

                    b.HasIndex("InstalledByUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PhoneMain");

                    b.HasIndex("PlanId");

                    b.HasIndex("TbnCode")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.ClientAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubidoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubidoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoDoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SubidoPorId");

                    b.ToTable("ClientAttachments");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.ClientQr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlertSent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeactivatedReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "IsActive");

                    b.HasIndex("ExpiresAt", "IsActive", "AlertSent");

                    b.ToTable("ClientQrs", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditApplied")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraordinaryReason")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsExtraordinary")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("ClientId", "Status");

                    b.HasIndex("ClientId", "Year", "Month", "Type")
                        .IsUnique();

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.InvoiceSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastValue")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InvoiceSequences");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Bank")
                        .HasColumnType("text");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("FromWhatsApp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVoided")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhysicalReceiptNumber")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoidJustification")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VoidedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaidAt");

                    b.HasIndex("RegisteredByUserId");

                    b.HasIndex("IsVoided", "PaidAt");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.PaymentInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentId", "InvoiceId")
                        .IsUnique();

                    b.ToTable("PaymentInvoices", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.PlanChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MidMonthChange")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NewPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OldPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessedById")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NewPlanId");

                    b.HasIndex("OldPlanId");

                    b.HasIndex("TicketId");

                    b.HasIndex("ClientId", "Status");

                    b.ToTable("PlanChangeRequests", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.ReceiptSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastValue")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ReceiptSequences");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.TbnSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastValue")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("TbnSequences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastValue = 0,
                            Prefix = "TBN"
                        });
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Dashboard.DashboardPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ShowComprobantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowDeudores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowKpis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowMetodosPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowTendencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowTickets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowWhatsApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowZonas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DashboardPreferences", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Installations.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CanceladoPor")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DuracionMin")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TicketId");

                    b.HasIndex("Fecha", "HoraInicio");

                    b.ToTable("Installations", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Notifications.NotifConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ActualizadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<int>("DelaySegundos")
                        .HasColumnType("integer");

                    b.Property<int?>("DiasAntes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<bool>("Inmediato")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlantillaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .IsUnique();

                    b.ToTable("NotifConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000001"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "SUSPENSION"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000002"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "REACTIVACION"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000003"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            DiasAntes = 5,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "RECORDATORIO_R1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000004"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            DiasAntes = 3,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "RECORDATORIO_R2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000005"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            DiasAntes = 1,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "RECORDATORIO_R3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000006"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 3600,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "FACTURA_VENCIDA"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000007"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = true,
                            Tipo = "CONFIRMACION_PAGO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000009"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "TICKET_CREADO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000010"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "TICKET_RESUELTO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000011"),
                            Activo = true,
                            ActualizadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaySegundos = 0,
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Inmediato = false,
                            Tipo = "CAMBIO_PLAN"
                        });
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Notifications.NotifLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("IntentoNum")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("RegistradoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "RegistradoAt");

                    b.HasIndex("ClienteId", "Tipo", "RegistradoAt");

                    b.ToTable("NotifLogs", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Notifications.NotifOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextoJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("CreadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnviarDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoFinal")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("PlantillaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcesadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProximoIntento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoFinal", "Publicado", "EnviarDesde");

                    b.ToTable("NotifOutbox", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Notifications.NotifPlantilla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("HsmStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Activa");

                    b.ToTable("NotifPlantillas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000001"),
                            Activa = true,
                            Categoria = "General",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\nSu servicio *{{plan}}* ha sido *suspendido* por falta de pago.\nComuníquese con nosotros para regularizar su cuenta.\n\n*TelecomBoliviaNet*",
                            Tipo = "SUSPENSION"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000002"),
                            Activa = true,
                            Categoria = "General",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\nSu servicio *{{plan}}* ha sido *reactivado* exitosamente. ¡Ya puede usarlo con normalidad!\n\n*TelecomBoliviaNet*",
                            Tipo = "REACTIVACION"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000003"),
                            Activa = true,
                            Categoria = "General",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\nLe recordamos que tiene una factura de *Bs. {{monto}}* con vencimiento el *{{fecha_vencimiento}}* ({{meses_pendientes}} mes(es) pendiente(s)).\n\nEvite inconvenientes pagando antes del vencimiento.\n\n*TelecomBoliviaNet*",
                            Tipo = "RECORDATORIO_R1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000004"),
                            Activa = true,
                            Categoria = "General",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\n⚠️ Su factura de *Bs. {{monto}}* vence el *{{fecha_vencimiento}}*. Evite la suspensión del servicio pagando a tiempo.\n\n*TelecomBoliviaNet*",
                            Tipo = "RECORDATORIO_R2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000005"),
                            Activa = true,
                            Categoria = "General",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\n🚨 Su factura vence *mañana* ({{fecha_vencimiento}}). Monto: *Bs. {{monto}}*.\nRealice su pago hoy para no perder el servicio.\n\n*TelecomBoliviaNet*",
                            Tipo = "RECORDATORIO_R3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000006"),
                            Activa = true,
                            Categoria = "General",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\nSu factura del periodo *{{periodo}}* por *Bs. {{monto}}* está *vencida*.\nPor favor regularice su pago para evitar la suspensión del servicio.\n\n*TelecomBoliviaNet*",
                            Tipo = "FACTURA_VENCIDA"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000007"),
                            Activa = true,
                            Categoria = "General",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\n✅ Hemos registrado su pago de *Bs. {{monto}}* correspondiente al periodo *{{periodo}}*.\n\nGracias por su pago puntual. *TelecomBoliviaNet*",
                            Tipo = "CONFIRMACION_PAGO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000009"),
                            Activa = true,
                            Categoria = "Ticket",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\nSu solicitud de soporte ha sido registrada con el número *{{num_ticket}}*.\n\nLe atenderemos a la brevedad. *{{empresa}}*",
                            Tipo = "TICKET_CREADO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000010"),
                            Activa = true,
                            Categoria = "Ticket",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\nSu ticket *{{num_ticket}}* ha sido *resuelto* por {{tecnico}}.\n\nSi tiene alguna consulta adicional, contáctenos. *{{empresa}}*",
                            Tipo = "TICKET_RESUELTO"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000011"),
                            Activa = true,
                            Categoria = "Cobro",
                            CreadoAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreadoPorId = new Guid("00000000-0000-0000-0000-000000000001"),
                            HsmStatus = "Aprobada",
                            Texto = "Estimado/a {{nombre}},\n\nSu plan de servicio ha sido actualizado a *{{plan}}*.\n\nEl cambio es efectivo inmediatamente. *{{empresa}}*",
                            Tipo = "CAMBIO_PLAN"
                        });
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Notifications.NotifPlantillaHistorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArchivadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivadoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlantillaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("NotifPlantillaHistorial", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Notifications.NotifSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActualizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReglasJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("NotifSegments", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Payments.CashClose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagosRechazados")
                        .HasColumnType("integer");

                    b.Property<int>("PagosValidados")
                        .HasColumnType("integer");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CashCloses");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Payments.PaymentReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Bank")
                        .HasColumnType("text");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GeneratedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvoiceNumbers")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SentByWhatsApp")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GeneratedById");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentReceipts");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Payments.WhatsAppReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DeclaredAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionNote")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("Status");

                    b.ToTable("WhatsAppReceipts", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpeedMb")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MonthlyPrice = 99.00m,
                            Name = "Plan Cobre",
                            SpeedMb = 30
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MonthlyPrice = 149.00m,
                            Name = "Plan Plata",
                            SpeedMb = 50
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MonthlyPrice = 199.00m,
                            Name = "Plan Oro",
                            SpeedMb = 80
                        });
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.SlaPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FirstResponseMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.ToTable("SlaPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstResponseMinutes = 15,
                            IsActive = true,
                            Name = "SLA Crítico",
                            Priority = "Critica",
                            ResolutionMinutes = 240,
                            Schedule = "Veinticuatro7"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstResponseMinutes = 30,
                            IsActive = true,
                            Name = "SLA Alto",
                            Priority = "Alta",
                            ResolutionMinutes = 480,
                            Schedule = "Veinticuatro7"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstResponseMinutes = 120,
                            IsActive = true,
                            Name = "SLA Medio",
                            Priority = "Media",
                            ResolutionMinutes = 1440,
                            Schedule = "Laboral"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstResponseMinutes = 240,
                            IsActive = true,
                            Name = "SLA Bajo",
                            Priority = "Baja",
                            ResolutionMinutes = 4320,
                            Schedule = "Laboral"
                        });
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoAssigned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CsatRespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CsatScore")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstRespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ResolutionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RootCause")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SlaAlertSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("SlaCompliant")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SlaDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SupportGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("SupportTickets", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubidoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubidoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubidoPorId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAttachments");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketNotifications", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastValue")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TicketSequences");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketVisits", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketWorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketWorkLogs", (string)null);
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Client", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "InstalledBy")
                        .WithMany()
                        .HasForeignKey("InstalledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Plans.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstalledBy");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.ClientAttachment", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.ClientQr", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Invoice", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Payment", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("RegisteredBy");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.PaymentInvoice", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Invoice", "Invoice")
                        .WithMany("PaymentInvoices")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Payment", "Payment")
                        .WithMany("PaymentInvoices")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.PlanChangeRequest", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Plans.Plan", "NewPlan")
                        .WithMany()
                        .HasForeignKey("NewPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Plans.Plan", "OldPlan")
                        .WithMany()
                        .HasForeignKey("OldPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("NewPlan");

                    b.Navigation("OldPlan");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Dashboard.DashboardPreference", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", null)
                        .WithOne()
                        .HasForeignKey("TelecomBoliviaNet.Domain.Entities.Dashboard.DashboardPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Installations.Installation", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Plans.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Plan");

                    b.Navigation("Tecnico");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Notifications.NotifLog", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Notifications.NotifOutbox", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Payments.CashClose", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Payments.PaymentReceipt", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "GeneratedBy")
                        .WithMany()
                        .HasForeignKey("GeneratedById");

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("GeneratedBy");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Payments.WhatsAppReceipt", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Client");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketAttachment", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubidoPor");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketComment", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketNotification", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", "Ticket")
                        .WithMany("Notifications")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketVisit", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", "Ticket")
                        .WithMany("Visits")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.TicketWorkLog", b =>
                {
                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", "Ticket")
                        .WithMany("WorkLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelecomBoliviaNet.Domain.Entities.Auth.UserSystem", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Client", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Invoice", b =>
                {
                    b.Navigation("PaymentInvoices");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Clients.Payment", b =>
                {
                    b.Navigation("PaymentInvoices");
                });

            modelBuilder.Entity("TelecomBoliviaNet.Domain.Entities.Tickets.SupportTicket", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Notifications");

                    b.Navigation("Visits");

                    b.Navigation("WorkLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
